# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vendor6 < Formula
  desc "vendor6 prototype"
  homepage "https://github.com/kusshi94/vendor6"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6/releases/download/v0.0.0/vendor6_Darwin_x86_64.tar.gz"
      sha256 "dca33ed9346eeb7001a49b794a517ecae3f29ea2a0aec8048e5f3bb798a3a1c3"

      def install
        bin.install "vendor6"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kusshi94/vendor6/releases/download/v0.0.0/vendor6_Darwin_arm64.tar.gz"
      sha256 "4c67a07aa7908539dbd2208729a2cd485483242dca1da1403a2643c009af5b88"

      def install
        bin.install "vendor6"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6/releases/download/v0.0.0/vendor6_Linux_x86_64.tar.gz"
      sha256 "5a1c189a1f7222b785a926ab53b66f8793a510f9f8e8ae5a2cae544ac243c101"

      def install
        bin.install "vendor6"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kusshi94/vendor6/releases/download/v0.0.0/vendor6_Linux_arm64.tar.gz"
      sha256 "ae458749e0bc196cfff0572dd9f47631cad349c5b409df068feede05a212aaaa"

      def install
        bin.install "vendor6"
      end
    end
  end
end
