# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vendor6Cli < Formula
  desc "An Interactive CLI tool to identify vendors by IPv6 address"
  homepage "https://github.com/kusshi94/vendor6-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.3/vendor6-cli_Darwin_x86_64.tar.gz"
      sha256 "5bebbf87facff07d6d2d5e5169a3862c58d739d029b9e5d66d93e8eda1c7a99e"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.3/vendor6-cli_Darwin_arm64.tar.gz"
      sha256 "c48c44632d02cac7a4ef6f020a1ffda4c0a56678cb92d01c7fa108f02647ff43"

      def install
        bin.install "vendor6-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.3/vendor6-cli_Linux_arm64.tar.gz"
      sha256 "3f861470b1847b2a63d9baf79dfc2d48ce492559a115d1ba22c6940e5329f792"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.3/vendor6-cli_Linux_x86_64.tar.gz"
      sha256 "5582a9585905137decbd66fc4b0f0a710bfdb6a04a838d54da7a751db4f7652b"

      def install
        bin.install "vendor6-cli"
      end
    end
  end
end
