# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vendor6Cli < Formula
  desc "An Interactive CLI tool to identify vendors by IPv6 address"
  homepage "https://github.com/kusshi94/vendor6-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.2/vendor6-cli_Darwin_arm64.tar.gz"
      sha256 "894bd1627be37eee9e0767d4bf2904836c4ae6e9fa652d53197a5dcc879898cc"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.2/vendor6-cli_Darwin_x86_64.tar.gz"
      sha256 "558b7ac0d2a8e9f77aa992f13447645ef2a62e28b747cfa45c98a1bba0b325ce"

      def install
        bin.install "vendor6-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.2/vendor6-cli_Linux_arm64.tar.gz"
      sha256 "25e59f0583ac770186aa5edfc6162519714d7544c9a0c384661a97e627187dca"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.2/vendor6-cli_Linux_x86_64.tar.gz"
      sha256 "76e800da4419f2855196da92c8f637b368210bfdadf268a1013158bd154800a5"

      def install
        bin.install "vendor6-cli"
      end
    end
  end
end
