# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vendor6Cli < Formula
  desc "An Interactive CLI tool to identify vendors by IPv6 address"
  homepage "https://github.com/kusshi94/vendor6-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.1/vendor6-cli_Darwin_arm64.tar.gz"
      sha256 "95045fab9b33e063679cea57392dac018876dee65297e8745fdf1ab889363311"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.1/vendor6-cli_Darwin_x86_64.tar.gz"
      sha256 "85d3e2ab6744e792023fd86c5037679836ecb1367255b13423aa689531320494"

      def install
        bin.install "vendor6-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.1/vendor6-cli_Linux_arm64.tar.gz"
      sha256 "d95bbf3e3f70ce9c9df685efa173ccab0c74dae6db32e2f123ce230286b45602"

      def install
        bin.install "vendor6-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kusshi94/vendor6-cli/releases/download/v0.2.1/vendor6-cli_Linux_x86_64.tar.gz"
      sha256 "3558363d87e76503f29194a6c1b5fd8b6b9410b3a983c6c35aa8285307251c92"

      def install
        bin.install "vendor6-cli"
      end
    end
  end
end
